### ISSUE TITLE
creatibutors: show a message when user clicks on "Save and add another"

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#189]
Currently when a user clicks on the `Save and add another` button the form follows the below flow:
1. Form submits
2. The added creatibutor is added in the external form i.e the main deposit form
3. The modal form is cleared

On step 3, the modal form is cleared and the user does not have visual feedback if the creator/contributor was added successfully in the deposit form unless they quit the modal and see the creator/contributor list.

We should
- [ ] Add a message indicating that the creator/contributor added successfully in one of the positions shown in the screenshot
- [ ] The message should be dismissable, automatically after x seconds, or the user can explicitly remove it. See SUI [Message](https://react.semantic-ui.com/collections/message/#types-dismissible-block)

## Screenshots
<img width="922" alt="Screenshot 2021-02-02 at 14 33 52" src="https://user-images.githubusercontent.com/22594783/106608286-7e000e80-6564-11eb-8175-9f458bd423f8.png">

**Comment by mb-wali** [comment]
## Issue Update
after a discussion - instead of showing a label or text saying that the contributor/creator has been added. we would update the button ```save and add another``` once the contributor/creator has been saved to ```Added``` for some seconds.
see screenshots
![1of3](https://user-images.githubusercontent.com/44528277/107212351-226fce00-6a07-11eb-8da2-6fac7cac2b26.png)
![2of3](https://user-images.githubusercontent.com/44528277/107212357-24d22800-6a07-11eb-89c8-67d4de9b4c36.png)
![3of3](https://user-images.githubusercontent.com/44528277/107212436-403d3300-6a07-11eb-9fbe-cf63f2fba398.png)

@zzacharo  does this make sense?
