### ISSUE TITLE
Test `DepositRecordSerializer`

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#26]
- [x] Test `serialize` method
- [x] Test `deserialize` method
- [x] Test `removeEmptyValues` method

**Comment by fenekku** [comment]
A corner case for removeEmptyValues came up

1- Create a record with 1 contributor
2- Edit and remove that 1 contributor

The backend now gets record without the contributor field. For a PUT call, we would expect the backend to remove the contributor. For a PATCH call, we would expect the backend to keep the contributor (only changes fields present in the request)... The only way to solve this correctly would be to diff the initial recod versus the to-be-submitted one.

Since we are going for PUT right now, we should be fine with removeEmptyValues. But we should keep a note of this somehow.
