### ISSUE TITLE
files: style uploader according to mockups

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/react-invenio-deposit#92]
Check the final mockups in https://github.com/inveniosoftware/react-invenio-deposit/issues/91 and implement the different views. 

**Note**: needed backend might not be there but we can implement all the views even as placeholders!

Style file uploader views
- [x] Style uploader when no file metadata exist
- [x] Style uploader when the record is marked as metadata only
- [x] Style uploader when file metadata exist on a draft record
- [x] Style uploader when a file upload is in progress on a draft record
- [x] Style uploader file list view on a published record

**Comment by zzacharo** [comment]
List of implemented views
- Style uploader when no file metadata exist
![Screenshot 2020-11-18 at 14 35 07](https://user-images.githubusercontent.com/22594783/99536960-552b9c80-29ab-11eb-95c4-0889604e467f.png)

- Style uploader when the record is marked as metadata only
![Screenshot 2020-11-18 at 14 39 15](https://user-images.githubusercontent.com/22594783/99537370-ddaa3d00-29ab-11eb-9a40-20299aa3914b.png)

- Style uploader when file metadata exist on a draft record
![Screenshot 2020-11-18 at 14 40 04](https://user-images.githubusercontent.com/22594783/99537448-f7e41b00-29ab-11eb-9ca1-132579d41e82.png)

- Style uploader when a file upload is in progress on a draft record
![Screenshot 2020-11-18 at 14 41 56](https://user-images.githubusercontent.com/22594783/99537656-3aa5f300-29ac-11eb-9730-afd6b844505d.png)

- Style uploader file list view on a published record
![Screenshot 2020-11-18 at 14 23 26](https://user-images.githubusercontent.com/22594783/99537708-4db8c300-29ac-11eb-98ef-be053be022c1.png)

**Comment by ntarocco** [comment]
Nice work! 👏 🚀 

My comments:
* "Drag and drop file" text looks quite big compared to the rest... I am not sure how many people they actually do that because it requires you to move windows around, I believe most are using the upload button? I would give more relevance to that, IMHO
* I would change the button label "Choose files" with "Upload from my computer" or something similar. I think users are more used to the upload term, WDYT? I have checked Google Drive, Dropbox and Google Photos and they all mention the word "Upload", "Upload files" , "Upload from computer"

**Comment by kprzerwa** [comment]
🚀 
IMO it would be better if they would be both centered as in
```
Drag and drop file(s)
         -or-
Upload from my computer

```

because then you make them visually equal, and they are noticed in the same time, if the Drag and drop is on the left then it is "more important" since the reader starts reading from the left
